env:
  browser: true
  es2021: true
extends:
  - airbnb-typescript/base
#  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
#  - jest
#rules:
#  jest/expect-expect:
#    - error
#    - assertFunctionNames:
#        - expect
#        - request.**.expect
#        - request.*.expect